import os
Import('env')

build_dir = env['BUILDPATH']
program_name = build_dir + '/eMesher.exe'

source_files = [
    'Mesh3D.cpp',
    'Mesher.cpp',
    'Mesher2D.cpp',
    'Mesher3D.cpp',
    'MeshFlow2D.cpp',
    'MeshFlow3D.cpp',
    'MeshIO.cpp',
    'Tetrahedralizator.cpp',
    '../thirdpart/tetgen/predicates.cxx',
    '../thirdpart/tetgen/tetgen.cxx',
    'main.cpp'
]

libs_name = [
    'pthread'
]

libs_path = [
    '/usr/local/lib',
]

rpath = []
rpath.append(build_dir)

env.Program(program_name,source_files,LIBS=libs_name,LIBPATH=libs_path, RPATH=rpath)