import os
Import('env')

program_name ='../build/eMesher.exe'

source_files = [
    'Mesh3D.cpp',
    'Mesher2D.cpp',
    'Mesher3D.cpp',
    'MeshFileUtility.cpp',
    'MeshFlow3D.cpp',
    'MeshFlowMT.cpp',
    'Tetrahedralizator.cpp',
    '../thirdpart/tetgen/predicates.cxx',
    '../thirdpart/tetgen/tetgen.cxx',
    'main.cpp'
]

libs_name = [
    'pthread'
]

libs_path = [
    '/usr/local/lib',
    '../build'
]

rpath = [
    '/usr/local/lib',
    '../build'
]
env.Program(program_name,source_files,LIBS=libs_name,LIBPATH=libs_path, RPATH=rpath)